# Site settings
author: Russell Macalintal
title: On To Bigger and Better Things
header-img: img/home-bg.png
email: russell.macalintal@gmail.com
copyright_name: Russell Macalintal
description: > # this means to ignore newlines until "baseurl:"
  A Journey to Reinvent My Career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  russell-macalintal

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
